name: CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout@v3
      - uses: action-setup@v2
        with:
          version: 7
      - uses: setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - run: npm install --frozen-lockfile
      - run: npm run lint && npm run build